; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
upload_protocol = esptool
framework = arduino
monitor_speed = 115200

; used microcontroller
board_build.mcu = esp32s3

; MCU frequency
board_build.f_cpu = 240000000L

lib_deps =
    m5stack/M5Unified@^0.2.14
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    # TCP version specific to the ESP32 (do not want to use "RPAsyncTCP")
    https://github.com/ESP32Async/AsyncTCP.git
    https://github.com/alanswx/ESPAsyncWiFiManager.git
    https://github.com/bblanchon/ArduinoJson.git
    https://github.com/m5stack/M5Unit-Sonic.git
    https://github.com/m5stack/M5-STHS34PF80.git

build_flags = 
    -D ASYNCWEBSERVER_REGEX
